modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/Spoiled/issues"
license="MIT"

[[mods]]
modId="spoiled"
version="${file.jarVersion}"
displayName="Spoiled"
displayURL="https://www.curseforge.com/minecraft/mc-mods/spoiled"
authors="Mrbysco, ShyNieke"
description='''
I'm sorry if I'm spoiling it for you. But you might wanna keep an eye on your food.
'''
[[dependencies.spoiled]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.spoiled]]
modId="neoforge"
mandatory=true
versionRange="[20.2.86,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="spoiled.mixins.json"
[[mixins]]
config="spoiled.forge.mixins.json"