modLoader="javafml"
loaderVersion="[3,)"
issueTrackerURL="https://github.com/Mrbysco/Spoiled/issues"
license="MIT"

[[mods]]
modId="spoiled"
version="${file.jarVersion}"
displayName="Spoiled"
displayURL="https://www.curseforge.com/minecraft/mc-mods/spoiled"
authors="Mrbysco, ShyNieke"
description='''
I'm sorry if I'm spoiling it for you. But you might wanna keep an eye on your food.
'''
[[dependencies.spoiled]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.spoiled]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.6.78-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="spoiled.mixins.json"
[[mixins]]
config="spoiled.neoforge.mixins.json"