# Project
version=9.0.0
group=com.mrbysco.spoiled

# Common
minecraft_version=1.21.8

# NeoForge
neo_version=21.8.36
neogradle.subsystems.parchment.minecraftVersion=1.21.8
neogradle.subsystems.parchment.mappingsVersion=2025.07.20
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.132.0+1.21.8
fabric_loader_version=0.17.2
cloth_config_version=19.0.147
mod_menu_version=15.0.0-beta.3

# Optional dependencies
jei_version=24.0.0.2
crafttweaker_version=21.0.21
curios_version=11.0.1+1.21.5
rei_version=20.0.811
architectury_version=17.0.8

# Mod options
mod_name=Spoiled
mod_author=Mrbysco
mod_id=spoiled

#Publishing
curseforge_id=364918
modrinth_id=FsHyEZFS

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false