# Project
version=7.0.1
group=com.mrbysco.spoiled

# Common
minecraft_version=1.21.5

# NeoForge
neo_version=21.5.92
neogradle.subsystems.parchment.minecraftVersion=1.21.5
neogradle.subsystems.parchment.mappingsVersion=2025.06.15
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.119.9+1.21.5
fabric_loader_version=0.16.13
cloth_config_version=18.0.145
mod_menu_version=14.0.0-rc.2

# Optional dependencies
jei_version=21.4.0.27
crafttweaker_version=21.0.21
curios_version=11.0.1+1.21.5
rei_version=19.0.809
architectury_version=16.1.4

# Mod options
mod_name=Spoiled
mod_author=Mrbysco
mod_id=spoiled

#Publishing
curseforge_id=364918
modrinth_id=FsHyEZFS

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false