# Project
version=6.2.3
group=com.mrbysco.spoiled

# Common
minecraft_version=1.21.1
neoform_version=1.21.1-20240808.144430
parchment_minecraft_version=1.21.1
parchment_mapping_version=2024.11.17

# NeoForge
neo_version=21.1.228

# Fabric
fabric_version=0.116.5+1.21.1
fabric_loader_version=0.17.2
cloth_config_version=15.0.140
mod_menu_version=11.0.3

# Optional dependencies
jei_version=19.27.0.340
crafttweaker_version=21.0.38
curios_version=9.5.1+1.21.1
rei_version=16.0.799
architectury_version=13.0.8
sable_version=1.2.2

# Mod options
mod_name=Spoiled
mod_author=Mrbysco
mod_id=spoiled

#Publishing
curseforge_id=364918
modrinth_id=FsHyEZFS

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false