plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id "net.neoforged.moddev" version "2.0.141"
    id 'net.darkhax.curseforgegradle'
    id 'com.modrinth.minotaur'
}

base {
    archivesName = "${mod_name}-neoforge-${minecraft_version}"
}

configurations {
    testmodImplementation.extendsFrom implementation
}
neoForge {
    version = "${neo_version}"

    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    def commonResources = project(':common').file("src/main/resources")

    runs {
        configureEach { model ->
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'fml.earlyprogresswindow', 'false'

            //Limit ram usage for the dev environment to 4GB
            jvmArguments.add('-Xmx4G')

            if (model.project.javaToolchains.launcherFor(java.toolchain).map { it.metadata.vendor }.getOrElse("").contains("JetBrains")) {
                jvmArguments.add("-XX:+AllowEnhancedClassRedefinition")
            }
        }

        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }

        data {
            clientData()

            programArguments.addAll(
                    '--mod', "${mod_id}",
                    '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath(),
                    '--existing', commonResources.getAbsolutePath()
            )
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet sourceSets.test
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    maven {
        name = "Illusive Soulworks maven"
        url = "https://maven.theillusivec4.top/"
    }
}

dependencies {
    compileOnly project(":common")

//    compileOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"
//    compileOnly "me.shedaniel:RoughlyEnoughItems-api-neoforge:${rei_version}"
//    compileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-neoforge:${rei_version}"
//
//    implementation "dev.architectury:architectury-neoforge:${architectury_version}"
//    implementation "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"

    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
    testCompileOnly "mezz.jei:jei-${minecraft_version}-common:${jei_version}"
//    implementation "com.blamejared.crafttweaker:CraftTweaker-neoforge-${minecraft_version}:${crafttweaker_version}"
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"
}

compileJava {
    source(project(":common").sourceSets.main.allSource)
}

sourcesJar {
    from project(":common").sourceSets.main.allJava
}

processResources {
    from project(":common").sourceSets.main.resources
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId base.archivesName.get()
            version project.version
            from components.java
        }
    }
    repositories {
        if (System.getenv().SAP_SECRET) {
            maven {
                url "https://maven.saps.dev/releases"
                credentials {
                    username = "mrbysco"
                    password = "${System.getenv().SAP_SECRET}"
                }
            }
        }
    }
}

if (System.getenv().CURSEFORGE_KEY) {
    task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
        apiToken = System.getenv().CURSEFORGE_KEY

        def mainFile = upload(project.curseforge_id, jar)
        mainFile.releaseType = 'beta'
        mainFile.addGameVersion "NeoForge"
        mainFile.addGameVersion "${minecraft_version}"
        mainFile.addGameVersion "Java 25"
        mainFile.addGameVersion('Server', 'Client')

        mainFile.changelog = file("$project.rootDir/changelog.md")
        mainFile.changelogType = 'markdown'

//        mainFile.addOptional("jei")
//        mainFile.addOptional("roughly-enough-items")
//        mainFile.addOptional("crafttweaker")
//        mainFile.addOptional("curios")
    }
}

if (System.getenv().MODRINTH_KEY) {
    String fileContents = file("$project.rootDir/changelog.md").text
    modrinth {
        token = System.getenv().MODRINTH_KEY
        projectId = project.modrinth_id
        versionType = "beta"
        versionName = "${mod_name} ${minecraft_version}"
        versionNumber = project.version
        uploadFile = jar
        changelog = fileContents
        gameVersions = ["${minecraft_version}"]
        loaders = ["neoforge"]

        dependencies {
//            optional.project "jei"
//            optional.project "rei"
//            optional.project "crafttweaker"
//            optional.project "curios"
        }
    }
}